# Generated by Django 5.0.1 on 2024-03-28 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersignup',
            old_name='latname',
            new_name='lastname',
        ),
    ]
