# Generated by Django 5.0.1 on 2024-04-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesapp', '0002_rename_latname_usersignup_lastname'),
    ]

    operations = [
        migrations.CreateModel(
            name='mynotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('tech_option', models.CharField(max_length=100)),
                ('myfile', models.FileField(upload_to='notesfiles')),
                ('desc', models.TextField()),
            ],
        ),
    ]
